package com.websharp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.websharp.dao.EntityUser;
import com.websharp.dao.EntityOrg;
import com.websharp.dao.EntityBillRecord;
import com.websharp.dao.EntityCustomer;
import com.websharp.dao.EntityCustomerPackage;
import com.websharp.dao.EntityCustomerResource;
import com.websharp.dao.EntityCustomerUser;
import com.websharp.dao.EntityPayAmountRecord;
import com.websharp.dao.EntityPlayRecord;
import com.websharp.dao.EntityAccountBook;
import com.websharp.dao.EntityCustomerOrder;
import com.websharp.dao.EntityCustomerOrderFee;
import com.websharp.dao.EntityCustomerOrderProduct;
import com.websharp.dao.EntityCustomerOrderResource;
import com.websharp.dao.EntityStaticData;
import com.websharp.dao.EntityOffer;
import com.websharp.dao.EntityProduct;
import com.websharp.dao.EntityNotice;
import com.websharp.dao.EntityWorkLogDg;
import com.websharp.dao.EntityWorkLogYe;
import com.websharp.dao.EntityWorkLogGh;
import com.websharp.dao.EntityCommand;
import com.websharp.dao.EntityClientConfig;
import com.websharp.dao.EntityPayOrder;

import com.websharp.dao.EntityUserDao;
import com.websharp.dao.EntityOrgDao;
import com.websharp.dao.EntityBillRecordDao;
import com.websharp.dao.EntityCustomerDao;
import com.websharp.dao.EntityCustomerPackageDao;
import com.websharp.dao.EntityCustomerResourceDao;
import com.websharp.dao.EntityCustomerUserDao;
import com.websharp.dao.EntityPayAmountRecordDao;
import com.websharp.dao.EntityPlayRecordDao;
import com.websharp.dao.EntityAccountBookDao;
import com.websharp.dao.EntityCustomerOrderDao;
import com.websharp.dao.EntityCustomerOrderFeeDao;
import com.websharp.dao.EntityCustomerOrderProductDao;
import com.websharp.dao.EntityCustomerOrderResourceDao;
import com.websharp.dao.EntityStaticDataDao;
import com.websharp.dao.EntityOfferDao;
import com.websharp.dao.EntityProductDao;
import com.websharp.dao.EntityNoticeDao;
import com.websharp.dao.EntityWorkLogDgDao;
import com.websharp.dao.EntityWorkLogYeDao;
import com.websharp.dao.EntityWorkLogGhDao;
import com.websharp.dao.EntityCommandDao;
import com.websharp.dao.EntityClientConfigDao;
import com.websharp.dao.EntityPayOrderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entityUserDaoConfig;
    private final DaoConfig entityOrgDaoConfig;
    private final DaoConfig entityBillRecordDaoConfig;
    private final DaoConfig entityCustomerDaoConfig;
    private final DaoConfig entityCustomerPackageDaoConfig;
    private final DaoConfig entityCustomerResourceDaoConfig;
    private final DaoConfig entityCustomerUserDaoConfig;
    private final DaoConfig entityPayAmountRecordDaoConfig;
    private final DaoConfig entityPlayRecordDaoConfig;
    private final DaoConfig entityAccountBookDaoConfig;
    private final DaoConfig entityCustomerOrderDaoConfig;
    private final DaoConfig entityCustomerOrderFeeDaoConfig;
    private final DaoConfig entityCustomerOrderProductDaoConfig;
    private final DaoConfig entityCustomerOrderResourceDaoConfig;
    private final DaoConfig entityStaticDataDaoConfig;
    private final DaoConfig entityOfferDaoConfig;
    private final DaoConfig entityProductDaoConfig;
    private final DaoConfig entityNoticeDaoConfig;
    private final DaoConfig entityWorkLogDgDaoConfig;
    private final DaoConfig entityWorkLogYeDaoConfig;
    private final DaoConfig entityWorkLogGhDaoConfig;
    private final DaoConfig entityCommandDaoConfig;
    private final DaoConfig entityClientConfigDaoConfig;
    private final DaoConfig entityPayOrderDaoConfig;

    private final EntityUserDao entityUserDao;
    private final EntityOrgDao entityOrgDao;
    private final EntityBillRecordDao entityBillRecordDao;
    private final EntityCustomerDao entityCustomerDao;
    private final EntityCustomerPackageDao entityCustomerPackageDao;
    private final EntityCustomerResourceDao entityCustomerResourceDao;
    private final EntityCustomerUserDao entityCustomerUserDao;
    private final EntityPayAmountRecordDao entityPayAmountRecordDao;
    private final EntityPlayRecordDao entityPlayRecordDao;
    private final EntityAccountBookDao entityAccountBookDao;
    private final EntityCustomerOrderDao entityCustomerOrderDao;
    private final EntityCustomerOrderFeeDao entityCustomerOrderFeeDao;
    private final EntityCustomerOrderProductDao entityCustomerOrderProductDao;
    private final EntityCustomerOrderResourceDao entityCustomerOrderResourceDao;
    private final EntityStaticDataDao entityStaticDataDao;
    private final EntityOfferDao entityOfferDao;
    private final EntityProductDao entityProductDao;
    private final EntityNoticeDao entityNoticeDao;
    private final EntityWorkLogDgDao entityWorkLogDgDao;
    private final EntityWorkLogYeDao entityWorkLogYeDao;
    private final EntityWorkLogGhDao entityWorkLogGhDao;
    private final EntityCommandDao entityCommandDao;
    private final EntityClientConfigDao entityClientConfigDao;
    private final EntityPayOrderDao entityPayOrderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entityUserDaoConfig = daoConfigMap.get(EntityUserDao.class).clone();
        entityUserDaoConfig.initIdentityScope(type);

        entityOrgDaoConfig = daoConfigMap.get(EntityOrgDao.class).clone();
        entityOrgDaoConfig.initIdentityScope(type);

        entityBillRecordDaoConfig = daoConfigMap.get(EntityBillRecordDao.class).clone();
        entityBillRecordDaoConfig.initIdentityScope(type);

        entityCustomerDaoConfig = daoConfigMap.get(EntityCustomerDao.class).clone();
        entityCustomerDaoConfig.initIdentityScope(type);

        entityCustomerPackageDaoConfig = daoConfigMap.get(EntityCustomerPackageDao.class).clone();
        entityCustomerPackageDaoConfig.initIdentityScope(type);

        entityCustomerResourceDaoConfig = daoConfigMap.get(EntityCustomerResourceDao.class).clone();
        entityCustomerResourceDaoConfig.initIdentityScope(type);

        entityCustomerUserDaoConfig = daoConfigMap.get(EntityCustomerUserDao.class).clone();
        entityCustomerUserDaoConfig.initIdentityScope(type);

        entityPayAmountRecordDaoConfig = daoConfigMap.get(EntityPayAmountRecordDao.class).clone();
        entityPayAmountRecordDaoConfig.initIdentityScope(type);

        entityPlayRecordDaoConfig = daoConfigMap.get(EntityPlayRecordDao.class).clone();
        entityPlayRecordDaoConfig.initIdentityScope(type);

        entityAccountBookDaoConfig = daoConfigMap.get(EntityAccountBookDao.class).clone();
        entityAccountBookDaoConfig.initIdentityScope(type);

        entityCustomerOrderDaoConfig = daoConfigMap.get(EntityCustomerOrderDao.class).clone();
        entityCustomerOrderDaoConfig.initIdentityScope(type);

        entityCustomerOrderFeeDaoConfig = daoConfigMap.get(EntityCustomerOrderFeeDao.class).clone();
        entityCustomerOrderFeeDaoConfig.initIdentityScope(type);

        entityCustomerOrderProductDaoConfig = daoConfigMap.get(EntityCustomerOrderProductDao.class).clone();
        entityCustomerOrderProductDaoConfig.initIdentityScope(type);

        entityCustomerOrderResourceDaoConfig = daoConfigMap.get(EntityCustomerOrderResourceDao.class).clone();
        entityCustomerOrderResourceDaoConfig.initIdentityScope(type);

        entityStaticDataDaoConfig = daoConfigMap.get(EntityStaticDataDao.class).clone();
        entityStaticDataDaoConfig.initIdentityScope(type);

        entityOfferDaoConfig = daoConfigMap.get(EntityOfferDao.class).clone();
        entityOfferDaoConfig.initIdentityScope(type);

        entityProductDaoConfig = daoConfigMap.get(EntityProductDao.class).clone();
        entityProductDaoConfig.initIdentityScope(type);

        entityNoticeDaoConfig = daoConfigMap.get(EntityNoticeDao.class).clone();
        entityNoticeDaoConfig.initIdentityScope(type);

        entityWorkLogDgDaoConfig = daoConfigMap.get(EntityWorkLogDgDao.class).clone();
        entityWorkLogDgDaoConfig.initIdentityScope(type);

        entityWorkLogYeDaoConfig = daoConfigMap.get(EntityWorkLogYeDao.class).clone();
        entityWorkLogYeDaoConfig.initIdentityScope(type);

        entityWorkLogGhDaoConfig = daoConfigMap.get(EntityWorkLogGhDao.class).clone();
        entityWorkLogGhDaoConfig.initIdentityScope(type);

        entityCommandDaoConfig = daoConfigMap.get(EntityCommandDao.class).clone();
        entityCommandDaoConfig.initIdentityScope(type);

        entityClientConfigDaoConfig = daoConfigMap.get(EntityClientConfigDao.class).clone();
        entityClientConfigDaoConfig.initIdentityScope(type);

        entityPayOrderDaoConfig = daoConfigMap.get(EntityPayOrderDao.class).clone();
        entityPayOrderDaoConfig.initIdentityScope(type);

        entityUserDao = new EntityUserDao(entityUserDaoConfig, this);
        entityOrgDao = new EntityOrgDao(entityOrgDaoConfig, this);
        entityBillRecordDao = new EntityBillRecordDao(entityBillRecordDaoConfig, this);
        entityCustomerDao = new EntityCustomerDao(entityCustomerDaoConfig, this);
        entityCustomerPackageDao = new EntityCustomerPackageDao(entityCustomerPackageDaoConfig, this);
        entityCustomerResourceDao = new EntityCustomerResourceDao(entityCustomerResourceDaoConfig, this);
        entityCustomerUserDao = new EntityCustomerUserDao(entityCustomerUserDaoConfig, this);
        entityPayAmountRecordDao = new EntityPayAmountRecordDao(entityPayAmountRecordDaoConfig, this);
        entityPlayRecordDao = new EntityPlayRecordDao(entityPlayRecordDaoConfig, this);
        entityAccountBookDao = new EntityAccountBookDao(entityAccountBookDaoConfig, this);
        entityCustomerOrderDao = new EntityCustomerOrderDao(entityCustomerOrderDaoConfig, this);
        entityCustomerOrderFeeDao = new EntityCustomerOrderFeeDao(entityCustomerOrderFeeDaoConfig, this);
        entityCustomerOrderProductDao = new EntityCustomerOrderProductDao(entityCustomerOrderProductDaoConfig, this);
        entityCustomerOrderResourceDao = new EntityCustomerOrderResourceDao(entityCustomerOrderResourceDaoConfig, this);
        entityStaticDataDao = new EntityStaticDataDao(entityStaticDataDaoConfig, this);
        entityOfferDao = new EntityOfferDao(entityOfferDaoConfig, this);
        entityProductDao = new EntityProductDao(entityProductDaoConfig, this);
        entityNoticeDao = new EntityNoticeDao(entityNoticeDaoConfig, this);
        entityWorkLogDgDao = new EntityWorkLogDgDao(entityWorkLogDgDaoConfig, this);
        entityWorkLogYeDao = new EntityWorkLogYeDao(entityWorkLogYeDaoConfig, this);
        entityWorkLogGhDao = new EntityWorkLogGhDao(entityWorkLogGhDaoConfig, this);
        entityCommandDao = new EntityCommandDao(entityCommandDaoConfig, this);
        entityClientConfigDao = new EntityClientConfigDao(entityClientConfigDaoConfig, this);
        entityPayOrderDao = new EntityPayOrderDao(entityPayOrderDaoConfig, this);

        registerDao(EntityUser.class, entityUserDao);
        registerDao(EntityOrg.class, entityOrgDao);
        registerDao(EntityBillRecord.class, entityBillRecordDao);
        registerDao(EntityCustomer.class, entityCustomerDao);
        registerDao(EntityCustomerPackage.class, entityCustomerPackageDao);
        registerDao(EntityCustomerResource.class, entityCustomerResourceDao);
        registerDao(EntityCustomerUser.class, entityCustomerUserDao);
        registerDao(EntityPayAmountRecord.class, entityPayAmountRecordDao);
        registerDao(EntityPlayRecord.class, entityPlayRecordDao);
        registerDao(EntityAccountBook.class, entityAccountBookDao);
        registerDao(EntityCustomerOrder.class, entityCustomerOrderDao);
        registerDao(EntityCustomerOrderFee.class, entityCustomerOrderFeeDao);
        registerDao(EntityCustomerOrderProduct.class, entityCustomerOrderProductDao);
        registerDao(EntityCustomerOrderResource.class, entityCustomerOrderResourceDao);
        registerDao(EntityStaticData.class, entityStaticDataDao);
        registerDao(EntityOffer.class, entityOfferDao);
        registerDao(EntityProduct.class, entityProductDao);
        registerDao(EntityNotice.class, entityNoticeDao);
        registerDao(EntityWorkLogDg.class, entityWorkLogDgDao);
        registerDao(EntityWorkLogYe.class, entityWorkLogYeDao);
        registerDao(EntityWorkLogGh.class, entityWorkLogGhDao);
        registerDao(EntityCommand.class, entityCommandDao);
        registerDao(EntityClientConfig.class, entityClientConfigDao);
        registerDao(EntityPayOrder.class, entityPayOrderDao);
    }
    
    public void clear() {
        entityUserDaoConfig.getIdentityScope().clear();
        entityOrgDaoConfig.getIdentityScope().clear();
        entityBillRecordDaoConfig.getIdentityScope().clear();
        entityCustomerDaoConfig.getIdentityScope().clear();
        entityCustomerPackageDaoConfig.getIdentityScope().clear();
        entityCustomerResourceDaoConfig.getIdentityScope().clear();
        entityCustomerUserDaoConfig.getIdentityScope().clear();
        entityPayAmountRecordDaoConfig.getIdentityScope().clear();
        entityPlayRecordDaoConfig.getIdentityScope().clear();
        entityAccountBookDaoConfig.getIdentityScope().clear();
        entityCustomerOrderDaoConfig.getIdentityScope().clear();
        entityCustomerOrderFeeDaoConfig.getIdentityScope().clear();
        entityCustomerOrderProductDaoConfig.getIdentityScope().clear();
        entityCustomerOrderResourceDaoConfig.getIdentityScope().clear();
        entityStaticDataDaoConfig.getIdentityScope().clear();
        entityOfferDaoConfig.getIdentityScope().clear();
        entityProductDaoConfig.getIdentityScope().clear();
        entityNoticeDaoConfig.getIdentityScope().clear();
        entityWorkLogDgDaoConfig.getIdentityScope().clear();
        entityWorkLogYeDaoConfig.getIdentityScope().clear();
        entityWorkLogGhDaoConfig.getIdentityScope().clear();
        entityCommandDaoConfig.getIdentityScope().clear();
        entityClientConfigDaoConfig.getIdentityScope().clear();
        entityPayOrderDaoConfig.getIdentityScope().clear();
    }

    public EntityUserDao getEntityUserDao() {
        return entityUserDao;
    }

    public EntityOrgDao getEntityOrgDao() {
        return entityOrgDao;
    }

    public EntityBillRecordDao getEntityBillRecordDao() {
        return entityBillRecordDao;
    }

    public EntityCustomerDao getEntityCustomerDao() {
        return entityCustomerDao;
    }

    public EntityCustomerPackageDao getEntityCustomerPackageDao() {
        return entityCustomerPackageDao;
    }

    public EntityCustomerResourceDao getEntityCustomerResourceDao() {
        return entityCustomerResourceDao;
    }

    public EntityCustomerUserDao getEntityCustomerUserDao() {
        return entityCustomerUserDao;
    }

    public EntityPayAmountRecordDao getEntityPayAmountRecordDao() {
        return entityPayAmountRecordDao;
    }

    public EntityPlayRecordDao getEntityPlayRecordDao() {
        return entityPlayRecordDao;
    }

    public EntityAccountBookDao getEntityAccountBookDao() {
        return entityAccountBookDao;
    }

    public EntityCustomerOrderDao getEntityCustomerOrderDao() {
        return entityCustomerOrderDao;
    }

    public EntityCustomerOrderFeeDao getEntityCustomerOrderFeeDao() {
        return entityCustomerOrderFeeDao;
    }

    public EntityCustomerOrderProductDao getEntityCustomerOrderProductDao() {
        return entityCustomerOrderProductDao;
    }

    public EntityCustomerOrderResourceDao getEntityCustomerOrderResourceDao() {
        return entityCustomerOrderResourceDao;
    }

    public EntityStaticDataDao getEntityStaticDataDao() {
        return entityStaticDataDao;
    }

    public EntityOfferDao getEntityOfferDao() {
        return entityOfferDao;
    }

    public EntityProductDao getEntityProductDao() {
        return entityProductDao;
    }

    public EntityNoticeDao getEntityNoticeDao() {
        return entityNoticeDao;
    }

    public EntityWorkLogDgDao getEntityWorkLogDgDao() {
        return entityWorkLogDgDao;
    }

    public EntityWorkLogYeDao getEntityWorkLogYeDao() {
        return entityWorkLogYeDao;
    }

    public EntityWorkLogGhDao getEntityWorkLogGhDao() {
        return entityWorkLogGhDao;
    }

    public EntityCommandDao getEntityCommandDao() {
        return entityCommandDao;
    }

    public EntityClientConfigDao getEntityClientConfigDao() {
        return entityClientConfigDao;
    }

    public EntityPayOrderDao getEntityPayOrderDao() {
        return entityPayOrderDao;
    }

}
