package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_PAY_AMOUNT_RECORD.
 */
public class EntityPayAmountRecord {

    public String AMOUNT;
    public String PAYMENT_DATE;
    public String PAYMENT_METHOD;
    public String OPERATION_TYPE;
    public String ORGANIZE_NAME;
    public String STAFF_NAME;
    public String BANK_NAME;
    public String INVOICE_NO;
    public String PAYMENT_ID;
    public String CERTIFIED_TYPE;
    public String REMARK;

    public EntityPayAmountRecord() {
    }

    public EntityPayAmountRecord(String AMOUNT, String PAYMENT_DATE, String PAYMENT_METHOD, String OPERATION_TYPE, String ORGANIZE_NAME, String STAFF_NAME, String BANK_NAME, String INVOICE_NO, String PAYMENT_ID, String CERTIFIED_TYPE, String REMARK) {
        this.AMOUNT = AMOUNT;
        this.PAYMENT_DATE = PAYMENT_DATE;
        this.PAYMENT_METHOD = PAYMENT_METHOD;
        this.OPERATION_TYPE = OPERATION_TYPE;
        this.ORGANIZE_NAME = ORGANIZE_NAME;
        this.STAFF_NAME = STAFF_NAME;
        this.BANK_NAME = BANK_NAME;
        this.INVOICE_NO = INVOICE_NO;
        this.PAYMENT_ID = PAYMENT_ID;
        this.CERTIFIED_TYPE = CERTIFIED_TYPE;
        this.REMARK = REMARK;
    }

    public String getAMOUNT() {
        return AMOUNT;
    }

    public void setAMOUNT(String AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    public String getPAYMENT_DATE() {
        return PAYMENT_DATE;
    }

    public void setPAYMENT_DATE(String PAYMENT_DATE) {
        this.PAYMENT_DATE = PAYMENT_DATE;
    }

    public String getPAYMENT_METHOD() {
        return PAYMENT_METHOD;
    }

    public void setPAYMENT_METHOD(String PAYMENT_METHOD) {
        this.PAYMENT_METHOD = PAYMENT_METHOD;
    }

    public String getOPERATION_TYPE() {
        return OPERATION_TYPE;
    }

    public void setOPERATION_TYPE(String OPERATION_TYPE) {
        this.OPERATION_TYPE = OPERATION_TYPE;
    }

    public String getORGANIZE_NAME() {
        return ORGANIZE_NAME;
    }

    public void setORGANIZE_NAME(String ORGANIZE_NAME) {
        this.ORGANIZE_NAME = ORGANIZE_NAME;
    }

    public String getSTAFF_NAME() {
        return STAFF_NAME;
    }

    public void setSTAFF_NAME(String STAFF_NAME) {
        this.STAFF_NAME = STAFF_NAME;
    }

    public String getBANK_NAME() {
        return BANK_NAME;
    }

    public void setBANK_NAME(String BANK_NAME) {
        this.BANK_NAME = BANK_NAME;
    }

    public String getINVOICE_NO() {
        return INVOICE_NO;
    }

    public void setINVOICE_NO(String INVOICE_NO) {
        this.INVOICE_NO = INVOICE_NO;
    }

    public String getPAYMENT_ID() {
        return PAYMENT_ID;
    }

    public void setPAYMENT_ID(String PAYMENT_ID) {
        this.PAYMENT_ID = PAYMENT_ID;
    }

    public String getCERTIFIED_TYPE() {
        return CERTIFIED_TYPE;
    }

    public void setCERTIFIED_TYPE(String CERTIFIED_TYPE) {
        this.CERTIFIED_TYPE = CERTIFIED_TYPE;
    }

    public String getREMARK() {
        return REMARK;
    }

    public void setREMARK(String REMARK) {
        this.REMARK = REMARK;
    }

}
