package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_STATIC_DATA.
 */
public class EntityStaticData {

    public String CODE_TYPE;
    public String CODE_VALUE;
    public String CODE_NAME;

    public EntityStaticData() {
    }

    public EntityStaticData(String CODE_TYPE, String CODE_VALUE, String CODE_NAME) {
        this.CODE_TYPE = CODE_TYPE;
        this.CODE_VALUE = CODE_VALUE;
        this.CODE_NAME = CODE_NAME;
    }

    public String getCODE_TYPE() {
        return CODE_TYPE;
    }

    public void setCODE_TYPE(String CODE_TYPE) {
        this.CODE_TYPE = CODE_TYPE;
    }

    public String getCODE_VALUE() {
        return CODE_VALUE;
    }

    public void setCODE_VALUE(String CODE_VALUE) {
        this.CODE_VALUE = CODE_VALUE;
    }

    public String getCODE_NAME() {
        return CODE_NAME;
    }

    public void setCODE_NAME(String CODE_NAME) {
        this.CODE_NAME = CODE_NAME;
    }

}
