package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_COMMAND.
 */
public class EntityCommand {

    public String BUSI_COMMAND_NAME;
    public String AUTH_OBJECT_NO;
    public String NE_COMMAND_NAME;
    public String CREATE_DATE;
    public String DEAL_STATE;
    public String CMD_STATE;
    public String CMD_CONFIRM_DATE;
    public String CMD_STATUS_INFO;
    public String ORGANIZE_NAME;
    public String STAFF_NAME;

    public EntityCommand() {
    }

    public EntityCommand(String BUSI_COMMAND_NAME, String AUTH_OBJECT_NO, String NE_COMMAND_NAME, String CREATE_DATE, String DEAL_STATE, String CMD_STATE, String CMD_CONFIRM_DATE, String CMD_STATUS_INFO, String ORGANIZE_NAME, String STAFF_NAME) {
        this.BUSI_COMMAND_NAME = BUSI_COMMAND_NAME;
        this.AUTH_OBJECT_NO = AUTH_OBJECT_NO;
        this.NE_COMMAND_NAME = NE_COMMAND_NAME;
        this.CREATE_DATE = CREATE_DATE;
        this.DEAL_STATE = DEAL_STATE;
        this.CMD_STATE = CMD_STATE;
        this.CMD_CONFIRM_DATE = CMD_CONFIRM_DATE;
        this.CMD_STATUS_INFO = CMD_STATUS_INFO;
        this.ORGANIZE_NAME = ORGANIZE_NAME;
        this.STAFF_NAME = STAFF_NAME;
    }

    public String getBUSI_COMMAND_NAME() {
        return BUSI_COMMAND_NAME;
    }

    public void setBUSI_COMMAND_NAME(String BUSI_COMMAND_NAME) {
        this.BUSI_COMMAND_NAME = BUSI_COMMAND_NAME;
    }

    public String getAUTH_OBJECT_NO() {
        return AUTH_OBJECT_NO;
    }

    public void setAUTH_OBJECT_NO(String AUTH_OBJECT_NO) {
        this.AUTH_OBJECT_NO = AUTH_OBJECT_NO;
    }

    public String getNE_COMMAND_NAME() {
        return NE_COMMAND_NAME;
    }

    public void setNE_COMMAND_NAME(String NE_COMMAND_NAME) {
        this.NE_COMMAND_NAME = NE_COMMAND_NAME;
    }

    public String getCREATE_DATE() {
        return CREATE_DATE;
    }

    public void setCREATE_DATE(String CREATE_DATE) {
        this.CREATE_DATE = CREATE_DATE;
    }

    public String getDEAL_STATE() {
        return DEAL_STATE;
    }

    public void setDEAL_STATE(String DEAL_STATE) {
        this.DEAL_STATE = DEAL_STATE;
    }

    public String getCMD_STATE() {
        return CMD_STATE;
    }

    public void setCMD_STATE(String CMD_STATE) {
        this.CMD_STATE = CMD_STATE;
    }

    public String getCMD_CONFIRM_DATE() {
        return CMD_CONFIRM_DATE;
    }

    public void setCMD_CONFIRM_DATE(String CMD_CONFIRM_DATE) {
        this.CMD_CONFIRM_DATE = CMD_CONFIRM_DATE;
    }

    public String getCMD_STATUS_INFO() {
        return CMD_STATUS_INFO;
    }

    public void setCMD_STATUS_INFO(String CMD_STATUS_INFO) {
        this.CMD_STATUS_INFO = CMD_STATUS_INFO;
    }

    public String getORGANIZE_NAME() {
        return ORGANIZE_NAME;
    }

    public void setORGANIZE_NAME(String ORGANIZE_NAME) {
        this.ORGANIZE_NAME = ORGANIZE_NAME;
    }

    public String getSTAFF_NAME() {
        return STAFF_NAME;
    }

    public void setSTAFF_NAME(String STAFF_NAME) {
        this.STAFF_NAME = STAFF_NAME;
    }

}
