package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_CUSTOMER_USER.
 */
public class EntityCustomerUser {

    public String PROD_INST_ID;
    public String CUST_ID;
    public String USER_NAME;
    public String SUBSCRIBER_TYPE;
    public String PLAN_NAME;
    public String TV_NUMBER;
    public String BILL_ID;
    public String SUB_BILL_ID;
    public String CREATE_ORG_ID;
    public String CREATE_OP_ID;
    public String CREATE_DATE;
    public String OWN_CORP_ORG_ID;
    public String CUST_ORDER_ID;
    public String OS_STATUS;
    public String PASSWORD;
    public String LOGIN_NAME;

    public EntityCustomerUser() {
    }

    public EntityCustomerUser(String PROD_INST_ID, String CUST_ID, String USER_NAME, String SUBSCRIBER_TYPE, String PLAN_NAME, String TV_NUMBER, String BILL_ID, String SUB_BILL_ID, String CREATE_ORG_ID, String CREATE_OP_ID, String CREATE_DATE, String OWN_CORP_ORG_ID, String CUST_ORDER_ID, String OS_STATUS, String PASSWORD, String LOGIN_NAME) {
        this.PROD_INST_ID = PROD_INST_ID;
        this.CUST_ID = CUST_ID;
        this.USER_NAME = USER_NAME;
        this.SUBSCRIBER_TYPE = SUBSCRIBER_TYPE;
        this.PLAN_NAME = PLAN_NAME;
        this.TV_NUMBER = TV_NUMBER;
        this.BILL_ID = BILL_ID;
        this.SUB_BILL_ID = SUB_BILL_ID;
        this.CREATE_ORG_ID = CREATE_ORG_ID;
        this.CREATE_OP_ID = CREATE_OP_ID;
        this.CREATE_DATE = CREATE_DATE;
        this.OWN_CORP_ORG_ID = OWN_CORP_ORG_ID;
        this.CUST_ORDER_ID = CUST_ORDER_ID;
        this.OS_STATUS = OS_STATUS;
        this.PASSWORD = PASSWORD;
        this.LOGIN_NAME = LOGIN_NAME;
    }

    public String getPROD_INST_ID() {
        return PROD_INST_ID;
    }

    public void setPROD_INST_ID(String PROD_INST_ID) {
        this.PROD_INST_ID = PROD_INST_ID;
    }

    public String getCUST_ID() {
        return CUST_ID;
    }

    public void setCUST_ID(String CUST_ID) {
        this.CUST_ID = CUST_ID;
    }

    public String getUSER_NAME() {
        return USER_NAME;
    }

    public void setUSER_NAME(String USER_NAME) {
        this.USER_NAME = USER_NAME;
    }

    public String getSUBSCRIBER_TYPE() {
        return SUBSCRIBER_TYPE;
    }

    public void setSUBSCRIBER_TYPE(String SUBSCRIBER_TYPE) {
        this.SUBSCRIBER_TYPE = SUBSCRIBER_TYPE;
    }

    public String getPLAN_NAME() {
        return PLAN_NAME;
    }

    public void setPLAN_NAME(String PLAN_NAME) {
        this.PLAN_NAME = PLAN_NAME;
    }

    public String getTV_NUMBER() {
        return TV_NUMBER;
    }

    public void setTV_NUMBER(String TV_NUMBER) {
        this.TV_NUMBER = TV_NUMBER;
    }

    public String getBILL_ID() {
        return BILL_ID;
    }

    public void setBILL_ID(String BILL_ID) {
        this.BILL_ID = BILL_ID;
    }

    public String getSUB_BILL_ID() {
        return SUB_BILL_ID;
    }

    public void setSUB_BILL_ID(String SUB_BILL_ID) {
        this.SUB_BILL_ID = SUB_BILL_ID;
    }

    public String getCREATE_ORG_ID() {
        return CREATE_ORG_ID;
    }

    public void setCREATE_ORG_ID(String CREATE_ORG_ID) {
        this.CREATE_ORG_ID = CREATE_ORG_ID;
    }

    public String getCREATE_OP_ID() {
        return CREATE_OP_ID;
    }

    public void setCREATE_OP_ID(String CREATE_OP_ID) {
        this.CREATE_OP_ID = CREATE_OP_ID;
    }

    public String getCREATE_DATE() {
        return CREATE_DATE;
    }

    public void setCREATE_DATE(String CREATE_DATE) {
        this.CREATE_DATE = CREATE_DATE;
    }

    public String getOWN_CORP_ORG_ID() {
        return OWN_CORP_ORG_ID;
    }

    public void setOWN_CORP_ORG_ID(String OWN_CORP_ORG_ID) {
        this.OWN_CORP_ORG_ID = OWN_CORP_ORG_ID;
    }

    public String getCUST_ORDER_ID() {
        return CUST_ORDER_ID;
    }

    public void setCUST_ORDER_ID(String CUST_ORDER_ID) {
        this.CUST_ORDER_ID = CUST_ORDER_ID;
    }

    public String getOS_STATUS() {
        return OS_STATUS;
    }

    public void setOS_STATUS(String OS_STATUS) {
        this.OS_STATUS = OS_STATUS;
    }

    public String getPASSWORD() {
        return PASSWORD;
    }

    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD;
    }

    public String getLOGIN_NAME() {
        return LOGIN_NAME;
    }

    public void setLOGIN_NAME(String LOGIN_NAME) {
        this.LOGIN_NAME = LOGIN_NAME;
    }

}
