package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_USER.
 */
public class EntityUser {

    public String opId;
    public String loginCode;
    public String loginPwd;
    public String token;
    public String staffName;

    public EntityUser() {
    }

    public EntityUser(String opId, String loginCode, String loginPwd, String token, String staffName) {
        this.opId = opId;
        this.loginCode = loginCode;
        this.loginPwd = loginPwd;
        this.token = token;
        this.staffName = staffName;
    }

    public String getOpId() {
        return opId;
    }

    public void setOpId(String opId) {
        this.opId = opId;
    }

    public String getLoginCode() {
        return loginCode;
    }

    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode;
    }

    public String getLoginPwd() {
        return loginPwd;
    }

    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getStaffName() {
        return staffName;
    }

    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

}
