package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_BILL_RECORD.
 */
public class EntityBillRecord {

    public String ACCT_ITEM_TYPE;
    public String TOTAL_AMOUNT;
    public String BILLING_CYCLE_ID;
    public String UNPAY_AMOUNT;
    public String PPY_AMOUNT;

    public EntityBillRecord() {
    }

    public EntityBillRecord(String ACCT_ITEM_TYPE, String TOTAL_AMOUNT, String BILLING_CYCLE_ID, String UNPAY_AMOUNT, String PPY_AMOUNT) {
        this.ACCT_ITEM_TYPE = ACCT_ITEM_TYPE;
        this.TOTAL_AMOUNT = TOTAL_AMOUNT;
        this.BILLING_CYCLE_ID = BILLING_CYCLE_ID;
        this.UNPAY_AMOUNT = UNPAY_AMOUNT;
        this.PPY_AMOUNT = PPY_AMOUNT;
    }

    public String getACCT_ITEM_TYPE() {
        return ACCT_ITEM_TYPE;
    }

    public void setACCT_ITEM_TYPE(String ACCT_ITEM_TYPE) {
        this.ACCT_ITEM_TYPE = ACCT_ITEM_TYPE;
    }

    public String getTOTAL_AMOUNT() {
        return TOTAL_AMOUNT;
    }

    public void setTOTAL_AMOUNT(String TOTAL_AMOUNT) {
        this.TOTAL_AMOUNT = TOTAL_AMOUNT;
    }

    public String getBILLING_CYCLE_ID() {
        return BILLING_CYCLE_ID;
    }

    public void setBILLING_CYCLE_ID(String BILLING_CYCLE_ID) {
        this.BILLING_CYCLE_ID = BILLING_CYCLE_ID;
    }

    public String getUNPAY_AMOUNT() {
        return UNPAY_AMOUNT;
    }

    public void setUNPAY_AMOUNT(String UNPAY_AMOUNT) {
        this.UNPAY_AMOUNT = UNPAY_AMOUNT;
    }

    public String getPPY_AMOUNT() {
        return PPY_AMOUNT;
    }

    public void setPPY_AMOUNT(String PPY_AMOUNT) {
        this.PPY_AMOUNT = PPY_AMOUNT;
    }

}
