package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_CLIENT_CONFIG.
 */
public class EntityClientConfig {

    public String ParamTypeCode;
    public String ParamTypeName;
    public String ParamTypeID;
    public String ParamName;
    public String ParamValue;
    public String Description;
    public String CreateTime;
    public String Creator;
    public String CreateIP;
    public String UpdateTime;
    public String Updater;
    public String UpdateIP;
    public Integer ID;

    public EntityClientConfig() {
    }

    public EntityClientConfig(String ParamTypeCode, String ParamTypeName, String ParamTypeID, String ParamName, String ParamValue, String Description, String CreateTime, String Creator, String CreateIP, String UpdateTime, String Updater, String UpdateIP, Integer ID) {
        this.ParamTypeCode = ParamTypeCode;
        this.ParamTypeName = ParamTypeName;
        this.ParamTypeID = ParamTypeID;
        this.ParamName = ParamName;
        this.ParamValue = ParamValue;
        this.Description = Description;
        this.CreateTime = CreateTime;
        this.Creator = Creator;
        this.CreateIP = CreateIP;
        this.UpdateTime = UpdateTime;
        this.Updater = Updater;
        this.UpdateIP = UpdateIP;
        this.ID = ID;
    }

    public String getParamTypeCode() {
        return ParamTypeCode;
    }

    public void setParamTypeCode(String ParamTypeCode) {
        this.ParamTypeCode = ParamTypeCode;
    }

    public String getParamTypeName() {
        return ParamTypeName;
    }

    public void setParamTypeName(String ParamTypeName) {
        this.ParamTypeName = ParamTypeName;
    }

    public String getParamTypeID() {
        return ParamTypeID;
    }

    public void setParamTypeID(String ParamTypeID) {
        this.ParamTypeID = ParamTypeID;
    }

    public String getParamName() {
        return ParamName;
    }

    public void setParamName(String ParamName) {
        this.ParamName = ParamName;
    }

    public String getParamValue() {
        return ParamValue;
    }

    public void setParamValue(String ParamValue) {
        this.ParamValue = ParamValue;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    public String getCreator() {
        return Creator;
    }

    public void setCreator(String Creator) {
        this.Creator = Creator;
    }

    public String getCreateIP() {
        return CreateIP;
    }

    public void setCreateIP(String CreateIP) {
        this.CreateIP = CreateIP;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

    public String getUpdater() {
        return Updater;
    }

    public void setUpdater(String Updater) {
        this.Updater = Updater;
    }

    public String getUpdateIP() {
        return UpdateIP;
    }

    public void setUpdateIP(String UpdateIP) {
        this.UpdateIP = UpdateIP;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

}
