package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_NOTICE.
 */
public class EntityNotice {

    public String REL_ID;
    public String CORP_ORG_ID;
    public String AFFICHE_ID;
    public String AFFICHE_ID1;
    public String AFFICHE_TITLE;
    public String AFFICHE_CONTENT;
    public String OP_ID;
    public String PUBLISHER_OP_ID;
    public String AFFICHE_LEVEL;
    public String AFFICHE_CLASS;
    public String AFFICHE_STATE;
    public String VALID_DATE;
    public String EXPIRE_DATE;
    public String PUBLISH_DATE;

    public EntityNotice() {
    }

    public EntityNotice(String REL_ID, String CORP_ORG_ID, String AFFICHE_ID, String AFFICHE_ID1, String AFFICHE_TITLE, String AFFICHE_CONTENT, String OP_ID, String PUBLISHER_OP_ID, String AFFICHE_LEVEL, String AFFICHE_CLASS, String AFFICHE_STATE, String VALID_DATE, String EXPIRE_DATE, String PUBLISH_DATE) {
        this.REL_ID = REL_ID;
        this.CORP_ORG_ID = CORP_ORG_ID;
        this.AFFICHE_ID = AFFICHE_ID;
        this.AFFICHE_ID1 = AFFICHE_ID1;
        this.AFFICHE_TITLE = AFFICHE_TITLE;
        this.AFFICHE_CONTENT = AFFICHE_CONTENT;
        this.OP_ID = OP_ID;
        this.PUBLISHER_OP_ID = PUBLISHER_OP_ID;
        this.AFFICHE_LEVEL = AFFICHE_LEVEL;
        this.AFFICHE_CLASS = AFFICHE_CLASS;
        this.AFFICHE_STATE = AFFICHE_STATE;
        this.VALID_DATE = VALID_DATE;
        this.EXPIRE_DATE = EXPIRE_DATE;
        this.PUBLISH_DATE = PUBLISH_DATE;
    }

    public String getREL_ID() {
        return REL_ID;
    }

    public void setREL_ID(String REL_ID) {
        this.REL_ID = REL_ID;
    }

    public String getCORP_ORG_ID() {
        return CORP_ORG_ID;
    }

    public void setCORP_ORG_ID(String CORP_ORG_ID) {
        this.CORP_ORG_ID = CORP_ORG_ID;
    }

    public String getAFFICHE_ID() {
        return AFFICHE_ID;
    }

    public void setAFFICHE_ID(String AFFICHE_ID) {
        this.AFFICHE_ID = AFFICHE_ID;
    }

    public String getAFFICHE_ID1() {
        return AFFICHE_ID1;
    }

    public void setAFFICHE_ID1(String AFFICHE_ID1) {
        this.AFFICHE_ID1 = AFFICHE_ID1;
    }

    public String getAFFICHE_TITLE() {
        return AFFICHE_TITLE;
    }

    public void setAFFICHE_TITLE(String AFFICHE_TITLE) {
        this.AFFICHE_TITLE = AFFICHE_TITLE;
    }

    public String getAFFICHE_CONTENT() {
        return AFFICHE_CONTENT;
    }

    public void setAFFICHE_CONTENT(String AFFICHE_CONTENT) {
        this.AFFICHE_CONTENT = AFFICHE_CONTENT;
    }

    public String getOP_ID() {
        return OP_ID;
    }

    public void setOP_ID(String OP_ID) {
        this.OP_ID = OP_ID;
    }

    public String getPUBLISHER_OP_ID() {
        return PUBLISHER_OP_ID;
    }

    public void setPUBLISHER_OP_ID(String PUBLISHER_OP_ID) {
        this.PUBLISHER_OP_ID = PUBLISHER_OP_ID;
    }

    public String getAFFICHE_LEVEL() {
        return AFFICHE_LEVEL;
    }

    public void setAFFICHE_LEVEL(String AFFICHE_LEVEL) {
        this.AFFICHE_LEVEL = AFFICHE_LEVEL;
    }

    public String getAFFICHE_CLASS() {
        return AFFICHE_CLASS;
    }

    public void setAFFICHE_CLASS(String AFFICHE_CLASS) {
        this.AFFICHE_CLASS = AFFICHE_CLASS;
    }

    public String getAFFICHE_STATE() {
        return AFFICHE_STATE;
    }

    public void setAFFICHE_STATE(String AFFICHE_STATE) {
        this.AFFICHE_STATE = AFFICHE_STATE;
    }

    public String getVALID_DATE() {
        return VALID_DATE;
    }

    public void setVALID_DATE(String VALID_DATE) {
        this.VALID_DATE = VALID_DATE;
    }

    public String getEXPIRE_DATE() {
        return EXPIRE_DATE;
    }

    public void setEXPIRE_DATE(String EXPIRE_DATE) {
        this.EXPIRE_DATE = EXPIRE_DATE;
    }

    public String getPUBLISH_DATE() {
        return PUBLISH_DATE;
    }

    public void setPUBLISH_DATE(String PUBLISH_DATE) {
        this.PUBLISH_DATE = PUBLISH_DATE;
    }

}
