package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_CUSTOMER_ORDER_PRODUCT.
 */
public class EntityCustomerOrderProduct {

    public String PROD_ORDER_ID;
    public String OFFER_ID;
    public String OFFER_NAME;
    public String SRVPKG_ID;
    public String SRVPKG_NAME;
    public String STATE;
    public String VALID_DATE;
    public String EXPIRE_DATE;

    public EntityCustomerOrderProduct() {
    }

    public EntityCustomerOrderProduct(String PROD_ORDER_ID, String OFFER_ID, String OFFER_NAME, String SRVPKG_ID, String SRVPKG_NAME, String STATE, String VALID_DATE, String EXPIRE_DATE) {
        this.PROD_ORDER_ID = PROD_ORDER_ID;
        this.OFFER_ID = OFFER_ID;
        this.OFFER_NAME = OFFER_NAME;
        this.SRVPKG_ID = SRVPKG_ID;
        this.SRVPKG_NAME = SRVPKG_NAME;
        this.STATE = STATE;
        this.VALID_DATE = VALID_DATE;
        this.EXPIRE_DATE = EXPIRE_DATE;
    }

    public String getPROD_ORDER_ID() {
        return PROD_ORDER_ID;
    }

    public void setPROD_ORDER_ID(String PROD_ORDER_ID) {
        this.PROD_ORDER_ID = PROD_ORDER_ID;
    }

    public String getOFFER_ID() {
        return OFFER_ID;
    }

    public void setOFFER_ID(String OFFER_ID) {
        this.OFFER_ID = OFFER_ID;
    }

    public String getOFFER_NAME() {
        return OFFER_NAME;
    }

    public void setOFFER_NAME(String OFFER_NAME) {
        this.OFFER_NAME = OFFER_NAME;
    }

    public String getSRVPKG_ID() {
        return SRVPKG_ID;
    }

    public void setSRVPKG_ID(String SRVPKG_ID) {
        this.SRVPKG_ID = SRVPKG_ID;
    }

    public String getSRVPKG_NAME() {
        return SRVPKG_NAME;
    }

    public void setSRVPKG_NAME(String SRVPKG_NAME) {
        this.SRVPKG_NAME = SRVPKG_NAME;
    }

    public String getSTATE() {
        return STATE;
    }

    public void setSTATE(String STATE) {
        this.STATE = STATE;
    }

    public String getVALID_DATE() {
        return VALID_DATE;
    }

    public void setVALID_DATE(String VALID_DATE) {
        this.VALID_DATE = VALID_DATE;
    }

    public String getEXPIRE_DATE() {
        return EXPIRE_DATE;
    }

    public void setEXPIRE_DATE(String EXPIRE_DATE) {
        this.EXPIRE_DATE = EXPIRE_DATE;
    }

}
