package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_WORK_LOG_DG.
 */
public class EntityWorkLogDg {

    public String OccurTime;
    public String UserID;
    public String UserName;
    public String OrgCode;
    public String ParamType;
    public String ParamValue;
    public String OfferID;
    public String ProdID;
    public String ProSubStatus;
    public String SubFunction;
    public String State;
    public String ID;
    public String StaffName;
    public String DeptName;
    public String TradeID;
    public String PayWay;
    public String Amt;
    public String PayState;
    public String PayMessage;
    public String AccountID;
    public String CustCode;
    public String OfferName;
    public String ProdName;
    public String Message;
    public String PayID;

    public EntityWorkLogDg() {
    }

    public EntityWorkLogDg(String OccurTime, String UserID, String UserName, String OrgCode, String ParamType, String ParamValue, String OfferID, String ProdID, String ProSubStatus, String SubFunction, String State, String ID, String StaffName, String DeptName, String TradeID, String PayWay, String Amt, String PayState, String PayMessage, String AccountID, String CustCode, String OfferName, String ProdName, String Message, String PayID) {
        this.OccurTime = OccurTime;
        this.UserID = UserID;
        this.UserName = UserName;
        this.OrgCode = OrgCode;
        this.ParamType = ParamType;
        this.ParamValue = ParamValue;
        this.OfferID = OfferID;
        this.ProdID = ProdID;
        this.ProSubStatus = ProSubStatus;
        this.SubFunction = SubFunction;
        this.State = State;
        this.ID = ID;
        this.StaffName = StaffName;
        this.DeptName = DeptName;
        this.TradeID = TradeID;
        this.PayWay = PayWay;
        this.Amt = Amt;
        this.PayState = PayState;
        this.PayMessage = PayMessage;
        this.AccountID = AccountID;
        this.CustCode = CustCode;
        this.OfferName = OfferName;
        this.ProdName = ProdName;
        this.Message = Message;
        this.PayID = PayID;
    }

    public String getOccurTime() {
        return OccurTime;
    }

    public void setOccurTime(String OccurTime) {
        this.OccurTime = OccurTime;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getOrgCode() {
        return OrgCode;
    }

    public void setOrgCode(String OrgCode) {
        this.OrgCode = OrgCode;
    }

    public String getParamType() {
        return ParamType;
    }

    public void setParamType(String ParamType) {
        this.ParamType = ParamType;
    }

    public String getParamValue() {
        return ParamValue;
    }

    public void setParamValue(String ParamValue) {
        this.ParamValue = ParamValue;
    }

    public String getOfferID() {
        return OfferID;
    }

    public void setOfferID(String OfferID) {
        this.OfferID = OfferID;
    }

    public String getProdID() {
        return ProdID;
    }

    public void setProdID(String ProdID) {
        this.ProdID = ProdID;
    }

    public String getProSubStatus() {
        return ProSubStatus;
    }

    public void setProSubStatus(String ProSubStatus) {
        this.ProSubStatus = ProSubStatus;
    }

    public String getSubFunction() {
        return SubFunction;
    }

    public void setSubFunction(String SubFunction) {
        this.SubFunction = SubFunction;
    }

    public String getState() {
        return State;
    }

    public void setState(String State) {
        this.State = State;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getStaffName() {
        return StaffName;
    }

    public void setStaffName(String StaffName) {
        this.StaffName = StaffName;
    }

    public String getDeptName() {
        return DeptName;
    }

    public void setDeptName(String DeptName) {
        this.DeptName = DeptName;
    }

    public String getTradeID() {
        return TradeID;
    }

    public void setTradeID(String TradeID) {
        this.TradeID = TradeID;
    }

    public String getPayWay() {
        return PayWay;
    }

    public void setPayWay(String PayWay) {
        this.PayWay = PayWay;
    }

    public String getAmt() {
        return Amt;
    }

    public void setAmt(String Amt) {
        this.Amt = Amt;
    }

    public String getPayState() {
        return PayState;
    }

    public void setPayState(String PayState) {
        this.PayState = PayState;
    }

    public String getPayMessage() {
        return PayMessage;
    }

    public void setPayMessage(String PayMessage) {
        this.PayMessage = PayMessage;
    }

    public String getAccountID() {
        return AccountID;
    }

    public void setAccountID(String AccountID) {
        this.AccountID = AccountID;
    }

    public String getCustCode() {
        return CustCode;
    }

    public void setCustCode(String CustCode) {
        this.CustCode = CustCode;
    }

    public String getOfferName() {
        return OfferName;
    }

    public void setOfferName(String OfferName) {
        this.OfferName = OfferName;
    }

    public String getProdName() {
        return ProdName;
    }

    public void setProdName(String ProdName) {
        this.ProdName = ProdName;
    }

    public String getMessage() {
        return Message;
    }

    public void setMessage(String Message) {
        this.Message = Message;
    }

    public String getPayID() {
        return PayID;
    }

    public void setPayID(String PayID) {
        this.PayID = PayID;
    }

}
