package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_CUSTOMER_ORDER.
 */
public class EntityCustomerOrder {

    public String CUST_ORDER_ID;
    public String PROD_ORDER_ID;
    public String BUSI_NAME;
    public String ORGANIZE_NAME;
    public String STAFF_NAME;
    public String DEV_NAME;
    public String PAY_TYPE;
    public String CREATE_DATE;
    public String REMARK;
    public String ORDER_STATE;

    public EntityCustomerOrder() {
    }

    public EntityCustomerOrder(String CUST_ORDER_ID, String PROD_ORDER_ID, String BUSI_NAME, String ORGANIZE_NAME, String STAFF_NAME, String DEV_NAME, String PAY_TYPE, String CREATE_DATE, String REMARK, String ORDER_STATE) {
        this.CUST_ORDER_ID = CUST_ORDER_ID;
        this.PROD_ORDER_ID = PROD_ORDER_ID;
        this.BUSI_NAME = BUSI_NAME;
        this.ORGANIZE_NAME = ORGANIZE_NAME;
        this.STAFF_NAME = STAFF_NAME;
        this.DEV_NAME = DEV_NAME;
        this.PAY_TYPE = PAY_TYPE;
        this.CREATE_DATE = CREATE_DATE;
        this.REMARK = REMARK;
        this.ORDER_STATE = ORDER_STATE;
    }

    public String getCUST_ORDER_ID() {
        return CUST_ORDER_ID;
    }

    public void setCUST_ORDER_ID(String CUST_ORDER_ID) {
        this.CUST_ORDER_ID = CUST_ORDER_ID;
    }

    public String getPROD_ORDER_ID() {
        return PROD_ORDER_ID;
    }

    public void setPROD_ORDER_ID(String PROD_ORDER_ID) {
        this.PROD_ORDER_ID = PROD_ORDER_ID;
    }

    public String getBUSI_NAME() {
        return BUSI_NAME;
    }

    public void setBUSI_NAME(String BUSI_NAME) {
        this.BUSI_NAME = BUSI_NAME;
    }

    public String getORGANIZE_NAME() {
        return ORGANIZE_NAME;
    }

    public void setORGANIZE_NAME(String ORGANIZE_NAME) {
        this.ORGANIZE_NAME = ORGANIZE_NAME;
    }

    public String getSTAFF_NAME() {
        return STAFF_NAME;
    }

    public void setSTAFF_NAME(String STAFF_NAME) {
        this.STAFF_NAME = STAFF_NAME;
    }

    public String getDEV_NAME() {
        return DEV_NAME;
    }

    public void setDEV_NAME(String DEV_NAME) {
        this.DEV_NAME = DEV_NAME;
    }

    public String getPAY_TYPE() {
        return PAY_TYPE;
    }

    public void setPAY_TYPE(String PAY_TYPE) {
        this.PAY_TYPE = PAY_TYPE;
    }

    public String getCREATE_DATE() {
        return CREATE_DATE;
    }

    public void setCREATE_DATE(String CREATE_DATE) {
        this.CREATE_DATE = CREATE_DATE;
    }

    public String getREMARK() {
        return REMARK;
    }

    public void setREMARK(String REMARK) {
        this.REMARK = REMARK;
    }

    public String getORDER_STATE() {
        return ORDER_STATE;
    }

    public void setORDER_STATE(String ORDER_STATE) {
        this.ORDER_STATE = ORDER_STATE;
    }

}
