package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_WORK_LOG_YE.
 */
public class EntityWorkLogYe {

    public String OccurTime;
    public String UserID;
    public String UserName;
    public String OrgCode;
    public String ParamType;
    public String ParamValue;
    public String State;
    public String ID;

    public EntityWorkLogYe() {
    }

    public EntityWorkLogYe(String OccurTime, String UserID, String UserName, String OrgCode, String ParamType, String ParamValue, String State, String ID) {
        this.OccurTime = OccurTime;
        this.UserID = UserID;
        this.UserName = UserName;
        this.OrgCode = OrgCode;
        this.ParamType = ParamType;
        this.ParamValue = ParamValue;
        this.State = State;
        this.ID = ID;
    }

    public String getOccurTime() {
        return OccurTime;
    }

    public void setOccurTime(String OccurTime) {
        this.OccurTime = OccurTime;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getOrgCode() {
        return OrgCode;
    }

    public void setOrgCode(String OrgCode) {
        this.OrgCode = OrgCode;
    }

    public String getParamType() {
        return ParamType;
    }

    public void setParamType(String ParamType) {
        this.ParamType = ParamType;
    }

    public String getParamValue() {
        return ParamValue;
    }

    public void setParamValue(String ParamValue) {
        this.ParamValue = ParamValue;
    }

    public String getState() {
        return State;
    }

    public void setState(String State) {
        this.State = State;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

}
