package com.websharp.dao;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_PRODUCT.
 */
public class EntityProduct  implements Serializable{

    public String ProdId;
    public String ProdName;
    public String OfferId;
    public Double Price;
    public String AllowEditPrice;

    public EntityProduct() {
    }

    public EntityProduct(String ProdId, String ProdName, String OfferId, Double Price, String AllowEditPrice) {
        this.ProdId = ProdId;
        this.ProdName = ProdName;
        this.OfferId = OfferId;
        this.Price = Price;
        this.AllowEditPrice = AllowEditPrice;
    }

    public String getProdId() {
        return ProdId;
    }

    public void setProdId(String ProdId) {
        this.ProdId = ProdId;
    }

    public String getProdName() {
        return ProdName;
    }

    public void setProdName(String ProdName) {
        this.ProdName = ProdName;
    }

    public String getOfferId() {
        return OfferId;
    }

    public void setOfferId(String OfferId) {
        this.OfferId = OfferId;
    }

    public Double getPrice() {
        return Price;
    }

    public void setPrice(Double Price) {
        this.Price = Price;
    }

    public String getAllowEditPrice() {
        return AllowEditPrice;
    }

    public void setAllowEditPrice(String AllowEditPrice) {
        this.AllowEditPrice = AllowEditPrice;
    }

}
