package com.websharp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.websharp.dao.EntityWorkLogDg;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_WORK_LOG_DG.
*/
public class EntityWorkLogDgDao extends AbstractDao<EntityWorkLogDg, Void> {

    public static final String TABLENAME = "ENTITY_WORK_LOG_DG";

    /**
     * Properties of entity EntityWorkLogDg.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property OccurTime = new Property(0, String.class, "OccurTime", false, "OCCUR_TIME");
        public final static Property UserID = new Property(1, String.class, "UserID", false, "USER_ID");
        public final static Property UserName = new Property(2, String.class, "UserName", false, "USER_NAME");
        public final static Property OrgCode = new Property(3, String.class, "OrgCode", false, "ORG_CODE");
        public final static Property ParamType = new Property(4, String.class, "ParamType", false, "PARAM_TYPE");
        public final static Property ParamValue = new Property(5, String.class, "ParamValue", false, "PARAM_VALUE");
        public final static Property OfferID = new Property(6, String.class, "OfferID", false, "OFFER_ID");
        public final static Property ProdID = new Property(7, String.class, "ProdID", false, "PROD_ID");
        public final static Property ProSubStatus = new Property(8, String.class, "ProSubStatus", false, "PRO_SUB_STATUS");
        public final static Property SubFunction = new Property(9, String.class, "SubFunction", false, "SUB_FUNCTION");
        public final static Property State = new Property(10, String.class, "State", false, "STATE");
        public final static Property ID = new Property(11, String.class, "ID", false, "ID");
        public final static Property StaffName = new Property(12, String.class, "StaffName", false, "STAFF_NAME");
        public final static Property DeptName = new Property(13, String.class, "DeptName", false, "DEPT_NAME");
        public final static Property TradeID = new Property(14, String.class, "TradeID", false, "TRADE_ID");
        public final static Property PayWay = new Property(15, String.class, "PayWay", false, "PAY_WAY");
        public final static Property Amt = new Property(16, String.class, "Amt", false, "AMT");
        public final static Property PayState = new Property(17, String.class, "PayState", false, "PAY_STATE");
        public final static Property PayMessage = new Property(18, String.class, "PayMessage", false, "PAY_MESSAGE");
        public final static Property AccountID = new Property(19, String.class, "AccountID", false, "ACCOUNT_ID");
        public final static Property CustCode = new Property(20, String.class, "CustCode", false, "CUST_CODE");
        public final static Property OfferName = new Property(21, String.class, "OfferName", false, "OFFER_NAME");
        public final static Property ProdName = new Property(22, String.class, "ProdName", false, "PROD_NAME");
        public final static Property Message = new Property(23, String.class, "Message", false, "MESSAGE");
        public final static Property PayID = new Property(24, String.class, "PayID", false, "PAY_ID");
    };


    public EntityWorkLogDgDao(DaoConfig config) {
        super(config);
    }
    
    public EntityWorkLogDgDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_WORK_LOG_DG' (" + //
                "'OCCUR_TIME' TEXT," + // 0: OccurTime
                "'USER_ID' TEXT," + // 1: UserID
                "'USER_NAME' TEXT," + // 2: UserName
                "'ORG_CODE' TEXT," + // 3: OrgCode
                "'PARAM_TYPE' TEXT," + // 4: ParamType
                "'PARAM_VALUE' TEXT," + // 5: ParamValue
                "'OFFER_ID' TEXT," + // 6: OfferID
                "'PROD_ID' TEXT," + // 7: ProdID
                "'PRO_SUB_STATUS' TEXT," + // 8: ProSubStatus
                "'SUB_FUNCTION' TEXT," + // 9: SubFunction
                "'STATE' TEXT," + // 10: State
                "'ID' TEXT," + // 11: ID
                "'STAFF_NAME' TEXT," + // 12: StaffName
                "'DEPT_NAME' TEXT," + // 13: DeptName
                "'TRADE_ID' TEXT," + // 14: TradeID
                "'PAY_WAY' TEXT," + // 15: PayWay
                "'AMT' TEXT," + // 16: Amt
                "'PAY_STATE' TEXT," + // 17: PayState
                "'PAY_MESSAGE' TEXT," + // 18: PayMessage
                "'ACCOUNT_ID' TEXT," + // 19: AccountID
                "'CUST_CODE' TEXT," + // 20: CustCode
                "'OFFER_NAME' TEXT," + // 21: OfferName
                "'PROD_NAME' TEXT," + // 22: ProdName
                "'MESSAGE' TEXT," + // 23: Message
                "'PAY_ID' TEXT);"); // 24: PayID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_WORK_LOG_DG'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityWorkLogDg entity) {
        stmt.clearBindings();
 
        String OccurTime = entity.getOccurTime();
        if (OccurTime != null) {
            stmt.bindString(1, OccurTime);
        }
 
        String UserID = entity.getUserID();
        if (UserID != null) {
            stmt.bindString(2, UserID);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(3, UserName);
        }
 
        String OrgCode = entity.getOrgCode();
        if (OrgCode != null) {
            stmt.bindString(4, OrgCode);
        }
 
        String ParamType = entity.getParamType();
        if (ParamType != null) {
            stmt.bindString(5, ParamType);
        }
 
        String ParamValue = entity.getParamValue();
        if (ParamValue != null) {
            stmt.bindString(6, ParamValue);
        }
 
        String OfferID = entity.getOfferID();
        if (OfferID != null) {
            stmt.bindString(7, OfferID);
        }
 
        String ProdID = entity.getProdID();
        if (ProdID != null) {
            stmt.bindString(8, ProdID);
        }
 
        String ProSubStatus = entity.getProSubStatus();
        if (ProSubStatus != null) {
            stmt.bindString(9, ProSubStatus);
        }
 
        String SubFunction = entity.getSubFunction();
        if (SubFunction != null) {
            stmt.bindString(10, SubFunction);
        }
 
        String State = entity.getState();
        if (State != null) {
            stmt.bindString(11, State);
        }
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(12, ID);
        }
 
        String StaffName = entity.getStaffName();
        if (StaffName != null) {
            stmt.bindString(13, StaffName);
        }
 
        String DeptName = entity.getDeptName();
        if (DeptName != null) {
            stmt.bindString(14, DeptName);
        }
 
        String TradeID = entity.getTradeID();
        if (TradeID != null) {
            stmt.bindString(15, TradeID);
        }
 
        String PayWay = entity.getPayWay();
        if (PayWay != null) {
            stmt.bindString(16, PayWay);
        }
 
        String Amt = entity.getAmt();
        if (Amt != null) {
            stmt.bindString(17, Amt);
        }
 
        String PayState = entity.getPayState();
        if (PayState != null) {
            stmt.bindString(18, PayState);
        }
 
        String PayMessage = entity.getPayMessage();
        if (PayMessage != null) {
            stmt.bindString(19, PayMessage);
        }
 
        String AccountID = entity.getAccountID();
        if (AccountID != null) {
            stmt.bindString(20, AccountID);
        }
 
        String CustCode = entity.getCustCode();
        if (CustCode != null) {
            stmt.bindString(21, CustCode);
        }
 
        String OfferName = entity.getOfferName();
        if (OfferName != null) {
            stmt.bindString(22, OfferName);
        }
 
        String ProdName = entity.getProdName();
        if (ProdName != null) {
            stmt.bindString(23, ProdName);
        }
 
        String Message = entity.getMessage();
        if (Message != null) {
            stmt.bindString(24, Message);
        }
 
        String PayID = entity.getPayID();
        if (PayID != null) {
            stmt.bindString(25, PayID);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntityWorkLogDg readEntity(Cursor cursor, int offset) {
        EntityWorkLogDg entity = new EntityWorkLogDg( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // OccurTime
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UserID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // UserName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // OrgCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ParamType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ParamValue
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // OfferID
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // ProdID
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ProSubStatus
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // SubFunction
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // State
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // ID
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // StaffName
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // DeptName
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // TradeID
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // PayWay
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // Amt
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // PayState
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // PayMessage
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // AccountID
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // CustCode
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // OfferName
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // ProdName
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // Message
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24) // PayID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityWorkLogDg entity, int offset) {
        entity.setOccurTime(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOrgCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setParamType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setParamValue(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOfferID(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setProdID(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setProSubStatus(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSubFunction(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setState(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setID(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setStaffName(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDeptName(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setTradeID(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setPayWay(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setAmt(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPayState(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setPayMessage(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setAccountID(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setCustCode(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setOfferName(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setProdName(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setMessage(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setPayID(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntityWorkLogDg entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntityWorkLogDg entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
