package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_CUSTOMER.
 */
public class EntityCustomer {

    public String CUST_ID;
    public String CUST_NAME;
    public String CREATE_DATE;
    public String CUST_PROP;
    public String CUST_CERT_TYPE;
    public String CUST_STATUS;
    public String CUST_TYPE;
    public String CUST_LEVEL;
    public String REGION_NAME1;
    public String REGION_NAME2;
    public String REGION_NAME3;
    public String LOUDONG;
    public String DOOR_DESC;
    public String CONTRACT_TYPE;
    public String ORGANIZE_NAME;
    public String STAFF_NAME;
    public String CUST_CODE;
    public String CONT_NAME;
    public String OWN_CORP_ORG;
    public String CONT_PHONE1;
    public String CONT_PHONE2;
    public String CUST_CERT_NO;
    public String CONT_MOBILE1;
    public String CONT_MOBILE2;
    public String REMARK;
    public String ACCT_ID;
    public String PAYMENT_METHOD;
    public String C;
    public String STD_ADDR_NAME;

    public EntityCustomer() {
    }

    public EntityCustomer(String CUST_ID, String CUST_NAME, String CREATE_DATE, String CUST_PROP, String CUST_CERT_TYPE, String CUST_STATUS, String CUST_TYPE, String CUST_LEVEL, String REGION_NAME1, String REGION_NAME2, String REGION_NAME3, String LOUDONG, String DOOR_DESC, String CONTRACT_TYPE, String ORGANIZE_NAME, String STAFF_NAME, String CUST_CODE, String CONT_NAME, String OWN_CORP_ORG, String CONT_PHONE1, String CONT_PHONE2, String CUST_CERT_NO, String CONT_MOBILE1, String CONT_MOBILE2, String REMARK, String ACCT_ID, String PAYMENT_METHOD, String C, String STD_ADDR_NAME) {
        this.CUST_ID = CUST_ID;
        this.CUST_NAME = CUST_NAME;
        this.CREATE_DATE = CREATE_DATE;
        this.CUST_PROP = CUST_PROP;
        this.CUST_CERT_TYPE = CUST_CERT_TYPE;
        this.CUST_STATUS = CUST_STATUS;
        this.CUST_TYPE = CUST_TYPE;
        this.CUST_LEVEL = CUST_LEVEL;
        this.REGION_NAME1 = REGION_NAME1;
        this.REGION_NAME2 = REGION_NAME2;
        this.REGION_NAME3 = REGION_NAME3;
        this.LOUDONG = LOUDONG;
        this.DOOR_DESC = DOOR_DESC;
        this.CONTRACT_TYPE = CONTRACT_TYPE;
        this.ORGANIZE_NAME = ORGANIZE_NAME;
        this.STAFF_NAME = STAFF_NAME;
        this.CUST_CODE = CUST_CODE;
        this.CONT_NAME = CONT_NAME;
        this.OWN_CORP_ORG = OWN_CORP_ORG;
        this.CONT_PHONE1 = CONT_PHONE1;
        this.CONT_PHONE2 = CONT_PHONE2;
        this.CUST_CERT_NO = CUST_CERT_NO;
        this.CONT_MOBILE1 = CONT_MOBILE1;
        this.CONT_MOBILE2 = CONT_MOBILE2;
        this.REMARK = REMARK;
        this.ACCT_ID = ACCT_ID;
        this.PAYMENT_METHOD = PAYMENT_METHOD;
        this.C = C;
        this.STD_ADDR_NAME = STD_ADDR_NAME;
    }

    public String getCUST_ID() {
        return CUST_ID;
    }

    public void setCUST_ID(String CUST_ID) {
        this.CUST_ID = CUST_ID;
    }

    public String getCUST_NAME() {
        return CUST_NAME;
    }

    public void setCUST_NAME(String CUST_NAME) {
        this.CUST_NAME = CUST_NAME;
    }

    public String getCREATE_DATE() {
        return CREATE_DATE;
    }

    public void setCREATE_DATE(String CREATE_DATE) {
        this.CREATE_DATE = CREATE_DATE;
    }

    public String getCUST_PROP() {
        return CUST_PROP;
    }

    public void setCUST_PROP(String CUST_PROP) {
        this.CUST_PROP = CUST_PROP;
    }

    public String getCUST_CERT_TYPE() {
        return CUST_CERT_TYPE;
    }

    public void setCUST_CERT_TYPE(String CUST_CERT_TYPE) {
        this.CUST_CERT_TYPE = CUST_CERT_TYPE;
    }

    public String getCUST_STATUS() {
        return CUST_STATUS;
    }

    public void setCUST_STATUS(String CUST_STATUS) {
        this.CUST_STATUS = CUST_STATUS;
    }

    public String getCUST_TYPE() {
        return CUST_TYPE;
    }

    public void setCUST_TYPE(String CUST_TYPE) {
        this.CUST_TYPE = CUST_TYPE;
    }

    public String getCUST_LEVEL() {
        return CUST_LEVEL;
    }

    public void setCUST_LEVEL(String CUST_LEVEL) {
        this.CUST_LEVEL = CUST_LEVEL;
    }

    public String getREGION_NAME1() {
        return REGION_NAME1;
    }

    public void setREGION_NAME1(String REGION_NAME1) {
        this.REGION_NAME1 = REGION_NAME1;
    }

    public String getREGION_NAME2() {
        return REGION_NAME2;
    }

    public void setREGION_NAME2(String REGION_NAME2) {
        this.REGION_NAME2 = REGION_NAME2;
    }

    public String getREGION_NAME3() {
        return REGION_NAME3;
    }

    public void setREGION_NAME3(String REGION_NAME3) {
        this.REGION_NAME3 = REGION_NAME3;
    }

    public String getLOUDONG() {
        return LOUDONG;
    }

    public void setLOUDONG(String LOUDONG) {
        this.LOUDONG = LOUDONG;
    }

    public String getDOOR_DESC() {
        return DOOR_DESC;
    }

    public void setDOOR_DESC(String DOOR_DESC) {
        this.DOOR_DESC = DOOR_DESC;
    }

    public String getCONTRACT_TYPE() {
        return CONTRACT_TYPE;
    }

    public void setCONTRACT_TYPE(String CONTRACT_TYPE) {
        this.CONTRACT_TYPE = CONTRACT_TYPE;
    }

    public String getORGANIZE_NAME() {
        return ORGANIZE_NAME;
    }

    public void setORGANIZE_NAME(String ORGANIZE_NAME) {
        this.ORGANIZE_NAME = ORGANIZE_NAME;
    }

    public String getSTAFF_NAME() {
        return STAFF_NAME;
    }

    public void setSTAFF_NAME(String STAFF_NAME) {
        this.STAFF_NAME = STAFF_NAME;
    }

    public String getCUST_CODE() {
        return CUST_CODE;
    }

    public void setCUST_CODE(String CUST_CODE) {
        this.CUST_CODE = CUST_CODE;
    }

    public String getCONT_NAME() {
        return CONT_NAME;
    }

    public void setCONT_NAME(String CONT_NAME) {
        this.CONT_NAME = CONT_NAME;
    }

    public String getOWN_CORP_ORG() {
        return OWN_CORP_ORG;
    }

    public void setOWN_CORP_ORG(String OWN_CORP_ORG) {
        this.OWN_CORP_ORG = OWN_CORP_ORG;
    }

    public String getCONT_PHONE1() {
        return CONT_PHONE1;
    }

    public void setCONT_PHONE1(String CONT_PHONE1) {
        this.CONT_PHONE1 = CONT_PHONE1;
    }

    public String getCONT_PHONE2() {
        return CONT_PHONE2;
    }

    public void setCONT_PHONE2(String CONT_PHONE2) {
        this.CONT_PHONE2 = CONT_PHONE2;
    }

    public String getCUST_CERT_NO() {
        return CUST_CERT_NO;
    }

    public void setCUST_CERT_NO(String CUST_CERT_NO) {
        this.CUST_CERT_NO = CUST_CERT_NO;
    }

    public String getCONT_MOBILE1() {
        return CONT_MOBILE1;
    }

    public void setCONT_MOBILE1(String CONT_MOBILE1) {
        this.CONT_MOBILE1 = CONT_MOBILE1;
    }

    public String getCONT_MOBILE2() {
        return CONT_MOBILE2;
    }

    public void setCONT_MOBILE2(String CONT_MOBILE2) {
        this.CONT_MOBILE2 = CONT_MOBILE2;
    }

    public String getREMARK() {
        return REMARK;
    }

    public void setREMARK(String REMARK) {
        this.REMARK = REMARK;
    }

    public String getACCT_ID() {
        return ACCT_ID;
    }

    public void setACCT_ID(String ACCT_ID) {
        this.ACCT_ID = ACCT_ID;
    }

    public String getPAYMENT_METHOD() {
        return PAYMENT_METHOD;
    }

    public void setPAYMENT_METHOD(String PAYMENT_METHOD) {
        this.PAYMENT_METHOD = PAYMENT_METHOD;
    }

    public String getC() {
        return C;
    }

    public void setC(String C) {
        this.C = C;
    }

    public String getSTD_ADDR_NAME() {
        return STD_ADDR_NAME;
    }

    public void setSTD_ADDR_NAME(String STD_ADDR_NAME) {
        this.STD_ADDR_NAME = STD_ADDR_NAME;
    }

}
