package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_CUSTOMER_PACKAGE.
 */
public class EntityCustomerPackage {

    public String OFFER_ID;
    public String OFFER_NAME;
    public String SRVPKG_ID;
    public String SRVPKG_NAME;
    public String OS_STATUS;
    public String VALID_DATE;
    public String EXPIRE_DATE;
    public String DONE_DATE;
    public String ORGANIZE_NAME;
    public String STAFF_NAME;
    public String END_DATE;

    public EntityCustomerPackage() {
    }

    public EntityCustomerPackage(String OFFER_ID, String OFFER_NAME, String SRVPKG_ID, String SRVPKG_NAME, String OS_STATUS, String VALID_DATE, String EXPIRE_DATE, String DONE_DATE, String ORGANIZE_NAME, String STAFF_NAME, String END_DATE) {
        this.OFFER_ID = OFFER_ID;
        this.OFFER_NAME = OFFER_NAME;
        this.SRVPKG_ID = SRVPKG_ID;
        this.SRVPKG_NAME = SRVPKG_NAME;
        this.OS_STATUS = OS_STATUS;
        this.VALID_DATE = VALID_DATE;
        this.EXPIRE_DATE = EXPIRE_DATE;
        this.DONE_DATE = DONE_DATE;
        this.ORGANIZE_NAME = ORGANIZE_NAME;
        this.STAFF_NAME = STAFF_NAME;
        this.END_DATE = END_DATE;
    }

    public String getOFFER_ID() {
        return OFFER_ID;
    }

    public void setOFFER_ID(String OFFER_ID) {
        this.OFFER_ID = OFFER_ID;
    }

    public String getOFFER_NAME() {
        return OFFER_NAME;
    }

    public void setOFFER_NAME(String OFFER_NAME) {
        this.OFFER_NAME = OFFER_NAME;
    }

    public String getSRVPKG_ID() {
        return SRVPKG_ID;
    }

    public void setSRVPKG_ID(String SRVPKG_ID) {
        this.SRVPKG_ID = SRVPKG_ID;
    }

    public String getSRVPKG_NAME() {
        return SRVPKG_NAME;
    }

    public void setSRVPKG_NAME(String SRVPKG_NAME) {
        this.SRVPKG_NAME = SRVPKG_NAME;
    }

    public String getOS_STATUS() {
        return OS_STATUS;
    }

    public void setOS_STATUS(String OS_STATUS) {
        this.OS_STATUS = OS_STATUS;
    }

    public String getVALID_DATE() {
        return VALID_DATE;
    }

    public void setVALID_DATE(String VALID_DATE) {
        this.VALID_DATE = VALID_DATE;
    }

    public String getEXPIRE_DATE() {
        return EXPIRE_DATE;
    }

    public void setEXPIRE_DATE(String EXPIRE_DATE) {
        this.EXPIRE_DATE = EXPIRE_DATE;
    }

    public String getDONE_DATE() {
        return DONE_DATE;
    }

    public void setDONE_DATE(String DONE_DATE) {
        this.DONE_DATE = DONE_DATE;
    }

    public String getORGANIZE_NAME() {
        return ORGANIZE_NAME;
    }

    public void setORGANIZE_NAME(String ORGANIZE_NAME) {
        this.ORGANIZE_NAME = ORGANIZE_NAME;
    }

    public String getSTAFF_NAME() {
        return STAFF_NAME;
    }

    public void setSTAFF_NAME(String STAFF_NAME) {
        this.STAFF_NAME = STAFF_NAME;
    }

    public String getEND_DATE() {
        return END_DATE;
    }

    public void setEND_DATE(String END_DATE) {
        this.END_DATE = END_DATE;
    }

}
