package com.websharp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.websharp.dao.EntityWorkLogGh;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_WORK_LOG_GH.
*/
public class EntityWorkLogGhDao extends AbstractDao<EntityWorkLogGh, Void> {

    public static final String TABLENAME = "ENTITY_WORK_LOG_GH";

    /**
     * Properties of entity EntityWorkLogGh.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property OccurTime = new Property(0, String.class, "OccurTime", false, "OCCUR_TIME");
        public final static Property UserID = new Property(1, String.class, "UserID", false, "USER_ID");
        public final static Property UserName = new Property(2, String.class, "UserName", false, "USER_NAME");
        public final static Property OrgCode = new Property(3, String.class, "OrgCode", false, "ORG_CODE");
        public final static Property OldStbNo = new Property(4, String.class, "OldStbNo", false, "OLD_STB_NO");
        public final static Property NewStbNo = new Property(5, String.class, "NewStbNo", false, "NEW_STB_NO");
        public final static Property Remark = new Property(6, String.class, "Remark", false, "REMARK");
        public final static Property State = new Property(7, String.class, "State", false, "STATE");
        public final static Property ID = new Property(8, String.class, "ID", false, "ID");
    };


    public EntityWorkLogGhDao(DaoConfig config) {
        super(config);
    }
    
    public EntityWorkLogGhDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_WORK_LOG_GH' (" + //
                "'OCCUR_TIME' TEXT," + // 0: OccurTime
                "'USER_ID' TEXT," + // 1: UserID
                "'USER_NAME' TEXT," + // 2: UserName
                "'ORG_CODE' TEXT," + // 3: OrgCode
                "'OLD_STB_NO' TEXT," + // 4: OldStbNo
                "'NEW_STB_NO' TEXT," + // 5: NewStbNo
                "'REMARK' TEXT," + // 6: Remark
                "'STATE' TEXT," + // 7: State
                "'ID' TEXT);"); // 8: ID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_WORK_LOG_GH'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityWorkLogGh entity) {
        stmt.clearBindings();
 
        String OccurTime = entity.getOccurTime();
        if (OccurTime != null) {
            stmt.bindString(1, OccurTime);
        }
 
        String UserID = entity.getUserID();
        if (UserID != null) {
            stmt.bindString(2, UserID);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(3, UserName);
        }
 
        String OrgCode = entity.getOrgCode();
        if (OrgCode != null) {
            stmt.bindString(4, OrgCode);
        }
 
        String OldStbNo = entity.getOldStbNo();
        if (OldStbNo != null) {
            stmt.bindString(5, OldStbNo);
        }
 
        String NewStbNo = entity.getNewStbNo();
        if (NewStbNo != null) {
            stmt.bindString(6, NewStbNo);
        }
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(7, Remark);
        }
 
        String State = entity.getState();
        if (State != null) {
            stmt.bindString(8, State);
        }
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(9, ID);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntityWorkLogGh readEntity(Cursor cursor, int offset) {
        EntityWorkLogGh entity = new EntityWorkLogGh( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // OccurTime
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UserID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // UserName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // OrgCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // OldStbNo
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // NewStbNo
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Remark
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // State
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // ID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityWorkLogGh entity, int offset) {
        entity.setOccurTime(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOrgCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOldStbNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNewStbNo(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRemark(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setState(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setID(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntityWorkLogGh entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntityWorkLogGh entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
