package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_CUSTOMER_ORDER_FEE.
 */
public class EntityCustomerOrderFee {

    public String PROD_ORDER_ID;
    public String PRICE_PLAN_NAME;
    public String SHOULD_MONEY;
    public String CUT_MONEY;
    public String FACT_MONEY;

    public EntityCustomerOrderFee() {
    }

    public EntityCustomerOrderFee(String PROD_ORDER_ID, String PRICE_PLAN_NAME, String SHOULD_MONEY, String CUT_MONEY, String FACT_MONEY) {
        this.PROD_ORDER_ID = PROD_ORDER_ID;
        this.PRICE_PLAN_NAME = PRICE_PLAN_NAME;
        this.SHOULD_MONEY = SHOULD_MONEY;
        this.CUT_MONEY = CUT_MONEY;
        this.FACT_MONEY = FACT_MONEY;
    }

    public String getPROD_ORDER_ID() {
        return PROD_ORDER_ID;
    }

    public void setPROD_ORDER_ID(String PROD_ORDER_ID) {
        this.PROD_ORDER_ID = PROD_ORDER_ID;
    }

    public String getPRICE_PLAN_NAME() {
        return PRICE_PLAN_NAME;
    }

    public void setPRICE_PLAN_NAME(String PRICE_PLAN_NAME) {
        this.PRICE_PLAN_NAME = PRICE_PLAN_NAME;
    }

    public String getSHOULD_MONEY() {
        return SHOULD_MONEY;
    }

    public void setSHOULD_MONEY(String SHOULD_MONEY) {
        this.SHOULD_MONEY = SHOULD_MONEY;
    }

    public String getCUT_MONEY() {
        return CUT_MONEY;
    }

    public void setCUT_MONEY(String CUT_MONEY) {
        this.CUT_MONEY = CUT_MONEY;
    }

    public String getFACT_MONEY() {
        return FACT_MONEY;
    }

    public void setFACT_MONEY(String FACT_MONEY) {
        this.FACT_MONEY = FACT_MONEY;
    }

}
