package com.websharp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_WORK_LOG_GH.
 */
public class EntityWorkLogGh {

    public String OccurTime;
    public String UserID;
    public String UserName;
    public String OrgCode;
    public String OldStbNo;
    public String NewStbNo;
    public String Remark;
    public String State;
    public String ID;

    public EntityWorkLogGh() {
    }

    public EntityWorkLogGh(String OccurTime, String UserID, String UserName, String OrgCode, String OldStbNo, String NewStbNo, String Remark, String State, String ID) {
        this.OccurTime = OccurTime;
        this.UserID = UserID;
        this.UserName = UserName;
        this.OrgCode = OrgCode;
        this.OldStbNo = OldStbNo;
        this.NewStbNo = NewStbNo;
        this.Remark = Remark;
        this.State = State;
        this.ID = ID;
    }

    public String getOccurTime() {
        return OccurTime;
    }

    public void setOccurTime(String OccurTime) {
        this.OccurTime = OccurTime;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getOrgCode() {
        return OrgCode;
    }

    public void setOrgCode(String OrgCode) {
        this.OrgCode = OrgCode;
    }

    public String getOldStbNo() {
        return OldStbNo;
    }

    public void setOldStbNo(String OldStbNo) {
        this.OldStbNo = OldStbNo;
    }

    public String getNewStbNo() {
        return NewStbNo;
    }

    public void setNewStbNo(String NewStbNo) {
        this.NewStbNo = NewStbNo;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getState() {
        return State;
    }

    public void setState(String State) {
        this.State = State;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

}
